#!/bin/bash

set -x -u -e -o pipefail

if [[ ! -f Dockerfile ]]; then
    echo "This script should be run from the repository root"
    exit 1
fi

COMMIT=$(git describe --dirty --tags)
BRANCH=$(git branch --show-current)
docker build --build-arg BRANCH="$BRANCH" --build-arg COMMIT="$COMMIT" -t "photomine:$BRANCH" .

if [[ "$BRANCH" = "master" ]]; then
    docker tag photomine:master photomine:latest
fi
